version: "3.8"
services:
  nexus:
    container_name: nexus-http
    image: sonatype/nexus3:latest
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=3703m
    ports:
      - "8081:8081" # для Web-UI интерфейса (можно использовать один и тот же порт)
    # Также мы монтируем директорию data текущей директории nexus3
    # внутрь контейнера (в директорию /nexus-data) для сохранения состояния
    # контейнера при его перезапусках. При использовании
    # в продуктивной инсталляции вы можете использовать Docker диск (volume),
    # расположенный на распределенной файловой системе
    volumes:
      - .\nexus-data:/nexus-data

    restart: unless-stopped
    networks:
      - nexus

networks:
  nexus:
    driver: bridge